pixman: Add an upstream patch to make it build with clang.
Pixman currently does not build with clang because of following error:
pixman-mmx.c:100:20: error: constraint 'K' expects an integer constant expression
        : "y" (__A), "K" (__N)

The error happens because __N is a function parameter and clang does not
process it as an integer literal by design.
Fix this by forcing the macro version of the function which exposes __N value
as an integer literal.

Also disable integrated assembler since clang's integerated assembler can't handle
pixman's assembly syntax.

BUG=chromium:793487
TEST=pixman builds with clang on caroline/kevin boards.

CQ-DEPEND=CL:818176

Change-Id: I82d608a440304f7743cfce2bc2ffce5b1e4f366f
Reviewed-on: https://chromium-review.googlesource.com/818306
Commit-Ready: Manoj Gupta <manojgupta@chromium.org>
Tested-by: Manoj Gupta <manojgupta@chromium.org>
Reviewed-by: Luis Lozano <llozano@chromium.org>