libtool: Update to upstream 2.4.6-r5.
Update libtool to current gentoo upstream.

Changes:
1. EAPI -> 5
2. KEYWORDS -> *
3. Add epatch "${PATCHES[@]}" to apply the patches.
4. Continue applying the clang library detection patch.
5. Drop pthread patch since arc builds do not support -lpthread
   (see errors below).

https://ci.chromium.org/p/chromeos/builds/b8946782423288239488
arc-mesa-17.3.0_rc5-r123: /bin/sh ../../libtool  --tag=CXX   --mode=link
/opt/android-n/arc-llvm/3.8/bin/clang++
--gcc-toolchain=/opt/android-n/arc-gcc/x86_64/x86_64-linux-android-4.9 -target
x86_64-linux-android -m32
-I/build/reef/opt/google/containers/android/usr/include/arch-x86/include/ -fvisibility=hidden
-Werror=vla -O2 -pipe -O2 -pipe -O2 -pipe -march=corei7 -g -fno-exceptions -fno-unwind-tables
-fno-asynchronous-unwind-tables --sysroot=/build/reef/opt/google/containers/android
--gcc-toolchain=/opt/android-n/arc-gcc/x86_64/x86_64-linux-android-4.9 -target
x86_64-linux-android -stdlib=libc++
-I/build/reef/opt/google/containers/android/usr/include/c++/4.9 -Wall -fno-math-errno
-fno-trapping-math -Qunused-arguments   -Wl,-O1 -Wl,-O2 -Wl,--as-needed -o spirv2nir
spirv/spirv2nir-spirv2nir.o nir/libnir.la ../../src/util/libmesautil.la -lm -pthread
arc-mesa-17.3.0_rc5-r123: libtool: link: /opt/android-n/arc-llvm/3.8/bin/clang++
--gcc-toolchain=/opt/android-n/arc-gcc/x86_64/x86_64-linux-android-4.9 -target
x86_64-linux-android -m32
-I/build/reef/opt/google/containers/android/usr/include/arch-x86/include/ -fvisibility=hidden
-Werror=vla -O2 -pipe -O2 -pipe -O2 -pipe -march=corei7 -g -fno-exceptions -fno-unwind-tables
-fno-asynchronous-unwind-tables --sysroot=/build/reef/opt/google/containers/android
--gcc-toolchain=/opt/android-n/arc-gcc/x86_64/x86_64-linux-android-4.9 -target
x86_64-linux-android -stdlib=libc++
-I/build/reef/opt/google/containers/android/usr/include/c++/4.9 -Wall -fno-math-errno
-fno-trapping-math -Qunused-arguments -Wl,-O1 -Wl,-O2 -Wl,--as-needed -o spirv2nir
spirv/spirv2nir-spirv2nir.o -pthread  nir/.libs/libnir.a ../../src/util/.libs/libmesautil.a
-L/build/reef/opt/google/containers/android/usr/lib -lz -latomic -lm -lpthread -pthread
arc-mesa-17.3.0_rc5-r123:
/opt/android-n/arc-gcc/x86_64/x86_64-linux-android-4.9/lib/gcc/x86_64-linux-android/4.9/../../../../x86_64-linux-android/bin/ld:
error: cannot find -lpthread

CQ-DEPEND=CL:1056037

BUG=chromium:842316
TEST=libtool builds
TEST=emerge-amd64-generic alsa-lib builds with sanitizer flags.

Change-Id: I4a51f2c9a5dfa587d86f4ba821925386da06f1c7
Reviewed-on: https://chromium-review.googlesource.com/1055882
Commit-Ready: Manoj Gupta <manojgupta@chromium.org>
Tested-by: Manoj Gupta <manojgupta@chromium.org>
Reviewed-by: Yunlian Jiang <yunlian@chromium.org>