xfsprogs: don't assume $BUILD_CC has fsmap.h just because $CC does
The $BUILD_CC toolchain might have an older set of Linux headers than
the $CC toolchain. It's generally unsafe to try to build both with the
same definitions, but in particular, this one can cause compilation
failures in the local crc32selftest build:

 In file included from crc32.c:37:
 In file included from ../include/xfs.h:37:
 ../include/xfs/linux.h:226:11: fatal error: 'linux/fsmap.h' file not found
 # include <linux/fsmap.h>
           ^~~~~~~~~~~~~~~

It's safe to always assume that the headers don't have getfsmap, since
the alternative just includes our local definitions anyway.

Move -DHAVE_GETFSMAP from $(PCFLAGS) (which gets used by both $BUILD_CC
and $CC) to $(CFLAGS) (which is only used by $CC).

Patch is submitted upstream at:
  http://lkml.kernel.org/m/20180906183529.117251-1-briannorris@chromium.org

Submitted gentoo PR here, since maintainer is slow:
  https://github.com/gentoo/gentoo/pull/10070

BUG=chromium:881145
TEST=precq, with and without upgraded linux-headers

Change-Id: Ief87748d7ae2374db6dfd35348ab02b643d90678
Signed-off-by: Brian Norris <briannorris@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1199879
Reviewed-by: Chirantan Ekbote <chirantan@chromium.org>