net-misc/taylor-uucp: Remove external function declarations in unix/init.c
That makes the code compile with fewer warnings, and gets rid of this error
with recent Chrome OS toolchains:

init.c:100:14: error: redeclaration of 'getcwd' must have the 'overloadable' attribute
extern char *getcwd ();

             ^
/build/amd64-generic/usr/include/bits/unistd.h:158:8: note: previous overload of function is here
__NTH (getcwd (char *const __clang_pass_object_size __buf, size_t __size))
       ^

BUG=none (CL:2400787 is the reason)
TEST=emerge-amd64-generic -av taylor-uucp
(gentoo PR: https://github.com/gentoo/gentoo/pull/17497)

Change-Id: I80be787a328cd4350769c284e1af0ab8cac972f3
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/portage-stable/+/2403000
Tested-by: Nicolas Boichat <drinkcat@chromium.org>
Commit-Queue: Nicolas Boichat <drinkcat@chromium.org>
Reviewed-by: Mike Frysinger <vapier@chromium.org>